- hosts: all

  vars:
    rev: master
    project_dir: /home/bhirbec/bitbot
    config: /tmp/bittrex.json

  tasks:
    # BUILD
    - name: Clone repository
      git: repo=git@bitbucket.org:bhirbec/bitbot.git dest={{project_dir}} accept_hostkey=yes

    - name: Fetch repository
      shell: git fetch origin chdir={{project_dir}}

    - name: Checkout {{rev}} branch
      shell: git reset --hard origin/{{rev}} chdir={{project_dir}}

    - name: Run make
      shell: make chdir={{project_dir}}

    # DEPLOY
    - include_vars:
        file: vars.yaml

    - name: Copy JSON config
      copy: src=secrets/bittrex.json dest={{config}}

    - name: Copy systemd conf
      become: true
      template: src=systemd/{{item}}.service dest=/etc/systemd/system/{{item}}.service
      with_items:
        - bittrex

    - name: reload systemd
      become: true
      shell: systemctl daemon-reload

    - name: Restart
      service: name={{item}} state=restarted
      become: true
      with_items:
        - bittrex
