- hosts: all

  vars:
    project_dir: /home/bhirbec/bitbot
    disk_dir: /media/bitbot-data

  tasks:
    # TODO: use shallow repo with depth=1?
    - name: Clone repository
      git: repo=https://github.com/bhirbec/bitbot.git dest={{project_dir}} accept_hostkey=yes
      sudo: no

    - name: Fetch repository
      shell: git fetch origin chdir={{project_dir}}

    - name: Checkout Master branch
      shell: git reset --hard origin/master chdir={{project_dir}}

    - name: Run make
      shell: make chdir={{project_dir}}

    - name: Copy record.conf
      template: src=upstart/record.conf dest=/etc/init/record.conf
      sudo: yes

    - name: Restart record
      command: service record restart
      sudo: yes

    - name: Copy web.conf
      template: src=upstart/web.conf dest=/etc/init/web.conf
      sudo: yes

    - name: Restart web service
      command: service web restart
      sudo: yes
