# TODO: move go install to makefile

- hosts: all

  vars:
    project_dir: /home/bhirbec/bitbot

  tasks:
    - name: Fetch repository
      shell: git fetch origin chdir={{project_dir}}

    - name: Checkout Master branch
      shell: git reset --hard origin/master chdir={{project_dir}}

    - name: go install bitbot/...
      shell: GOPATH={{project_dir}} go install bitbot/...

    - name: Bundle javascript
      shell: make js chdir={{project_dir}}

    - name: Copy record.conf
      template: src=upstart/record.conf dest=/etc/init/record.conf
      sudo: yes

    - name: Restart record
      command: service record restart
      sudo: yes

    - name: Copy web.conf
      template: src=upstart/web.conf dest=/etc/init/web.conf
      sudo: yes

    - name: Restart web service
      command: service web restart
      sudo: yes
