- hosts: all

  vars:
    dev: false
    rev: master
    project_dir: /home/bhirbec/bitbot
    config: /tmp/config.json

  tasks:
    # BUILD
    - name: Fetch repository
      shell: git fetch origin chdir={{project_dir}}
      when: not dev

    - name: Checkout {{rev}} branch
      shell: git reset --hard origin/{{rev}} chdir={{project_dir}}
      when: not dev

    - name: Run make
      shell: make chdir={{project_dir}}

    # DEPLOY
    - include_vars:
        file: vars.yaml

    - name: Copy JSON config
      copy: src=secrets/config.json dest={{config}} # TODO: template this with vars.yaml

    - name: Copy systemd conf
      become: true
      template: src=systemd/{{item}}.service dest=/etc/systemd/system/{{item}}.service
      with_items:
        - trader

    - name: reload systemd
      become: true
      shell: systemctl daemon-reload

    - name: Restart
      service: name={{item}} state=restarted
      become: true
      with_items:
        - trader
