# TODO: update to node 4.2

- hosts: all
  sudo: yes

  vars:
    go_version: 1.4.1
    mysql_db: bitbot
    mysql_root_pwd: password
    mysql_user: bitbot
    mysql_user_pwd: password

  tasks:
    - name: Download APT packages
      apt: name={{item}} update_cache=true
      with_items:
        - gcc
        - git
        - build-essential
        - curl

    - name: Download Go
      shell: curl https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz | tar -v -C /usr/local/ -xz
      # [WARNING]: Consider using get_url module rather than running curl

    - name: Create symlinks to Go binaries
      shell: ln -fs /usr/local/go/bin/go /usr/local/bin
      # [WARNING]: Consider using file module with state=link rather than running ln

    # Node.js install
    - name: Add Node.js repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: Add Node.js repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node {{ansible_distribution_release}} main'

    - name: Install Node.js
      apt: pkg=nodejs

    # MySQL 5.7 install (http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-installing)
    - name: Add APT key for mysql 5.7
      apt_key:
        data: "{{ lookup('file', 'mysql/apt.key') }}"

    - name: Copy mysql.list
      copy: src=mysql/mysql.list dest=/etc/apt/sources.list.d/mysql.list

    - name: Setup MySQL password
      shell: |
        debconf-set-selections <<< 'mysql-server mysql-server/root_password password {{ mysql_root_pwd }}'
        debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password {{ mysql_root_pwd }}'
      args:
        executable: /bin/bash

    - name: Install MySQL packages
      apt: name=mysql-server update_cache=true

    - name: Setup database
      shell: |
        mysql -u root -e "
          create database if not exists {{ mysql_db }};
          create user if not exists '{{ mysql_user }}' identified by '{{ mysql_user_pwd }}';
          grant all privileges on {{ mysql_db }} . * to {{ mysql_user }};
        "
